config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, path: '/i_am_loyal_to_trident', :controllers => { :registrations => "employees/registrations" }
  devise_for :users, path: 'users'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :appointments
  root 'appointments#index'
  get "/all_apt", to: "appointments#printall"
  get '/users' => "appointments#printall", :as => :user_root
  get '/i_am_loyal_to_trident' => "records#index", :as => :employee_root
  get '/i_am_loyal_to_trident/print_all' => "records#print_all", :as => :employee_print_all
  get '/i_am_loyal_to_trident/show/:id' => "records#show", :as => :employee_show_apt
  get '/i_am_loyal_to_trident/approved/:id'=> "records#approved", :as => :approved
  get '/i_am_loyal_to_trident/time_conflict/:id'=> "records#time_conflict", :as => :time_conflict
  get '/i_am_loyal_to_trident/cancel/:id' => "records#destroy", :as => :employee_cancel_apt
  get '/i_am_loyal_to_trident/restrict/:day'=>"records#restrict_day", :as=> :restrict
  get '/i_am_loyal_to_trident/reset'=>"records#reset_restrict", :as=> :reset
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
	before_action :authenticate_employee!, except: []
	before_action :find_apt, only: [:show, :approved, :time_conflict, :destroy]

	def index
	end

	def print_all
		@appointment=Appointment.all
		@profit=Appointment.where(status:"approved").sum(:price)
		restrict_string
	end

	def show
		@email=User.find(@appointment.user_id).email
	end

	def approved
		@appointment.status= "approved"
		@appointment.save
		redirect_to employee_print_all_path
	end
	
	def time_conflict
		@appointment.status= "Time Conflict"
		@appointment.save
		redirect_to employee_print_all_path
	end


	def destroy
		@appointment.destroy
		redirect_to employee_print_all_path
	end

	def restrict_day
		if $restrict.include?(params[:day])
			$restrict.delete(params[:day])
		else
			$restrict.append(params[:day])
		end
		$restrict.sort
		restrict_string
		redirect_to employee_print_all_path
	end

	def reset_restrict
		$restrict=[]
		$restrict_day=["None"]
		redirect_to employee_print_all_path
	end



	private
	def find_apt
		@appointment=Appointment.find(params[:id])
	end

	def restrict_string
		$restrict_day=[]
		if $restrict.include?("1")
			$restrict_day.append("Monday")
		end
		if $restrict.include?("2")
			$restrict_day.append("Tuesday")
		end
		if $restrict.include?("3")
			$restrict_day.append("Wednesday")
		end
		if $restrict.include?("4")
			$restrict_day.append("Thursday")
		end
		if $restrict.include?("5")
			$restrict_day.append("Friday")
		end
		if $restrict.include?("6")
			$restrict_day.append("Saturday")
		end
		if $restrict.include?("7")
			$restrict_day.append("Sunday")
		end
	end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/index.html.haml
%h2="Welcome "+current_employee.First_name

app/views/records/print_all.html.haml
-@appointment.each do |apt|
 %h2= link_to apt.time, employee_show_apt_path(apt)
 %p= apt.status

%h3= "Current Profit"
%p=@profit
%h4="Click to restrict appoinments for the following days of the week"
=link_to "Monday", restrict_path(1)
=link_to "Tuesday", restrict_path(2)
=link_to "Wednesday", restrict_path(3)
=link_to "Thursday", restrict_path(4)
=link_to "Friday", restrict_path(5)
=link_to "Saturday", restrict_path(6)
=link_to "Sunday", restrict_path(7)
=link_to "Reset", reset_path
%h5= "The following days are currently not avaliable for this week"
-$restrict_day.each do |day|
 %p=day

app/views/records/show.html.haml
%h1= @appointment.service
%p= @appointment.time
%p= @appointment.vehicle_type
%p= @appointment.price
=mail_to @email
%p= @appointment.status


= link_to "Approved", approved_path(@appointment.id)
= link_to "Time Conflict",time_conflict_path(@appointment.id)
= link_to "Cancel", employee_cancel_apt_path(@appointment.id), data:{confirm: "Cancel Appointment?"}
= link_to "Home", root_path