config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, path: '/i_am_loyal_to_trident', :controllers => { :registrations => "employees/registrations" }
  devise_for :users, path: 'users'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :appointments
  root 'appointments#index'
  get "/all_apt", to: "appointments#printall"
  get '/users' => "appointments#printall", :as => :user_root
  get '/i_am_loyal_to_trident' => "records#index", :as => :employee_root
  get '/i_am_loyal_to_trident/print_all' => "records#print_all", :as => :employee_print_all
  get '/i_am_loyal_to_trident/show/:id' => "records#show", :as => :employee_show_apt
  get '/i_am_loyal_to_trident/approved/:id'=> "records#approved", :as => :approved
  get '/i_am_loyal_to_trident/time_conflict/:id'=> "records#time_conflict", :as => :time_conflict
  get '/i_am_loyal_to_trident/cancel/:id' => "records#destroy", :as => :employee_cancel_apt
  get '/i_am_loyal_to_trident/restrict/:day'=>"records#restrict_day", :as=> :restrict
  get '/i_am_loyal_to_trident/reset'=>"records#reset_restrict", :as=> :reset
end

app/models/appointment.rb
class Appointment < ApplicationRecord
	belongs_to :user
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
	before_action :find_apt, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index]

	def index
		@appointments=Appointment.all.order("created_at DESC")
	end

	def show
	end

	def new
		@appointment=current_user.appointments.build
	end

	def create
		@appointment=current_user.appointments.build(apt_params)
		set_price
		
		if @appointment.save
			redirect_to @appointment
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		set_price
		if @appointment.update(apt_params)	
			redirect_to @appointment
		else
			render 'edit'
		end
	end

	def destroy
		@appointment.destroy
		redirect_to '/all_apt'
	end

	def printall
		@appointment=Appointment.where("user_id=?",current_user.id)
	end

	def employee_option
	end

	private
	def find_apt
		@appointment=Appointment.find(params[:id])
	end

	def apt_params
		params.require(:appointment).permit(:service, :time, :vehicle_vin, :vehicle_name, :vehicle_manufacture, :vehicle_type, :vehicle_year, :vehicle_license_plate_num)
	end

	def set_price
		price=0.0
		case @appointment.service
		when "Full detail"
			if @appointment.vehicle_type=="Regular"
				price=80.0
			else
				price=85.0
			end
		when "Interior", "Exterior"
			if @appointment.vehicle_type=="Regular"
				price=45.0
			else
				price=50.0
			end
		when "Ceramic pro"
			if @appointment.vehicle_type=="Regular"
				price=1200.0
			else
				price=1300.0
			end
		when "Paint correction"
			if @appointment.vehicle_type=="Regular"
				price=250.0
			else
				price=300.0
			end
		end
		@appointment.price=price
	end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_editform.html.haml
%p="Time format: mm/dd/yy:hh:mm(24h format)"
=simple_form_for @appointment do |f|
	= f.input :service, collection: [ "Full detail", "Interior", "Exterior", "Ceramic pro", "Paint correction"], required: true
	= f.input :time, required: true
	= f.input :vehicle_vin, required: true
	= f.input :vehicle_name, required: true
	= f.input :vehicle_manufacture, required: true
	= f.input :vehicle_type, collection: [ "Regular", "SUV"], required: true
	= f.input :vehicle_year, required: true
	= f.input :vehicle_license_plate_num, required: true
	= f.input :price, readonly: true, required: true
	= f.input :status, readonly: true, required: true
	= f.button :submit

app/views/appointments/_form.html.haml
%p="Time format: mm/dd/yy:hh:mm(24h format)"
=simple_form_for @appointment do |f|
	= f.error_notification 
	= f.input :service, collection: [ "Full detail", "Interior", "Exterior", "Ceramic pro", "Paint correction"], required: true
	= f.input :time, "data-provide" => 'datepicker' , required: true
	= f.input :vehicle_vin, required: true
	= f.input :vehicle_name, required: true
	= f.input :vehicle_manufacture, required: true
	= f.input :vehicle_type, collection: [ "Regular", "SUV"], required: true
	= f.input :vehicle_year, required: true
	= f.input :vehicle_license_plate_num, required: true
	= f.button :submit

app/views/appointments/edit.html.haml
%h1 Edit
%h2= "Appointments on the following days will not be approved"
-$restrict_day.each do |day|
 %p=day
= render 'editform'

app/views/appointments/employee_option.html.haml
%h2="Employee option"

app/views/appointments/index.html.haml
= image_tag('trident.png', width: '400px') 
%p="At Trident Auto & Home Care Ltd. We focus on our customers satisfaction more than anything else. We offer professional detailing services including Interior and Exterior Detail; Shampoo services for carpets and seats, paint correction in 3 stages (Stage 1,2,3) along with Ceramic Coatings varying from 2 year warranties to lifetime warranty. We use the brand CeramicPro which is the highest quality brand in the market backed by a full warranty and various benefits including a water beading effect, prevention from oxidization and more.. it leaves your vehicles with a high gloss shine. We also offer ceramic coating for accessories such as bags, purses, shoes, wallets, etc. This product leaves your leather or textiles protected for months/years to come. The item will not stain and will not get as dirty so quick. We offer mobile services & we are flexible when it comes to your schedule we make it work! Prices vary for our work but the more often or more work you get done we offer loyalty discounts with our Trident Member Plans."

%h2= "Sample Pictures"
= image_tag('whole_before',width: '300px')
= image_tag('whole_after',width: '300px')
= image_tag('tire_before',width: '300px',height: "200")
= image_tag('tire_after',width: '300px',height: "200")

app/views/appointments/new.html.haml
%h1 New Appointment
%h2= "Appointments on the following days will not be approved"
-$restrict_day.each do |day|
 %p=day
= render 'form'

app/views/appointments/printall.html.haml
-@appointment.each do |apt|
 %h2= link_to apt.time, apt
=link_to "Make New Appointment", new_appointment_path

app/views/appointments/show.html.haml
%h1= @appointment.service
%p= @appointment.time
%p= @appointment.vehicle_type
%p= @appointment.price
%p= @appointment.status

= link_to "Edit", edit_appointment_path(@appointment)
= link_to "Cancel", appointment_path(@appointment), method: :delete, data:{confirm: "Cancel Appointment?"}
= link_to "Home", root_path