config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, path: '/i_am_loyal_to_trident', :controllers => { :registrations => "employees/registrations" }
  devise_for :users, path: 'users'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :appointments
  root 'appointments#index'
  get "/all_apt", to: "appointments#printall"
  get '/users' => "appointments#printall", :as => :user_root
  get '/i_am_loyal_to_trident' => "records#index", :as => :employee_root
  get '/i_am_loyal_to_trident/print_all' => "records#print_all", :as => :employee_print_all
  get '/i_am_loyal_to_trident/show/:id' => "records#show", :as => :employee_show_apt
  get '/i_am_loyal_to_trident/approved/:id'=> "records#approved", :as => :approved
  get '/i_am_loyal_to_trident/time_conflict/:id'=> "records#time_conflict", :as => :time_conflict
  get '/i_am_loyal_to_trident/cancel/:id' => "records#destroy", :as => :employee_cancel_apt
  get '/i_am_loyal_to_trident/restrict/:day'=>"records#restrict_day", :as=> :restrict
  get '/i_am_loyal_to_trident/reset'=>"records#reset_restrict", :as=> :reset
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trident Auto Care</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-default" role="navigation">
      <div class="navbar-inner">
        <div class="container">
          <div id="logo" class="navbar-brand"><%= link_to "Trident Auto Care", root_path %></div>
          <nav class="collapse navbar-collapse navbar-ex1-colapse">
            <% if user_signed_in? -%>
             <ul class="nav navbar-nav navbar-right">
              <li><%= link_to current_user.First_name, edit_user_registration_path %></li>
              <li><%= link_to "Make Appointment", new_appointment_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, :method=> :delete %></li>
            </ul>
            <% elsif employee_signed_in? -%>
             <ul class="nav navbar-nav navbar-right">
              <li><%= link_to current_employee.First_name, edit_employee_registration_path %></li>
              <li><%= link_to "List Appointments", employee_print_all_path %></li>              
              <li><%= link_to "Sign Out", destroy_employee_session_path, :method=> :delete %></li>
            </ul>
            <% else -%>
              <ul class="nav navbar-nav pull-right">
                <li><%= link_to "Sign Up", new_user_registration_path %></li>
                <li><%= link_to "Sign In", new_user_session_path %></li>
              </ul>
            <% end -%>
          </nav>
        </div>
      </div>
    </header>

    <div id="main" class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-%{name}") %>
        <% end %>
    <div id="container" class="col-md-9 center-block">
      
      <%= yield %>
    </div>
  </div>
  </body>
</html>